print("Please enter five numbers:")
num1 = int(input())
num2 = int(input())
num3 = int(input())
num4 = int(input())
num5 = int(input())
print("The average of those numbers is: ")
print(str((num1 + num2 + num3 + num4 + num5)/5))
